Feature/qase
PatternsG/Graduation_Project_By_QASE pull request #2
Opened 2022-09-16 09:15 UTC by PatternsG

2022-09-16 21:05 UTC, voropa requested changes
У вас очень много захардкоданых тестовых данных / индексов в page методах. Так не должно быть. Все тестовые данные и т.д. должны попадать в методы через входные аргументы.

2022-09-16 21:05 UTC, voropa commented on src/main/resources/allure.properties
> +allure.link.issue.pattern = https://instagram.com/{}
Удалите эти проперти, если они у вас не используются

2022-09-16 21:05 UTC, voropa commented on src/test/java/UI/Allure/AllureUtils.java
> +public class AllureUtils extends BaseTest {
А зачем его экстендить от BaseTest?

2022-09-16 21:05 UTC, voropa commented on src/test/java/UI/Allure/TestListener.java
> +        System.out.println("Test " + result.getName() + " started");
Замените все system.out на logger

2022-09-16 21:05 UTC, voropa commented on src/test/java/UI/Elements/NewSuitePage/Input.java
> +public class Input extends BaseElement {
У вас два одинаковых декоратора Input c идентичными методами и локаторами, можно отсавить один?

2022-09-16 21:05 UTC, voropa commented on src/test/java/UI/Elements/NewTestCasePage/Input.java
> +public class Input extends BaseElement {
Точнее даже 3 одинаковых Input декоратора

2022-09-16 21:05 UTC, voropa commented on src/test/java/UI/Elements/TestCasePage/Combobox.java
> +    private final String COMBOBOX_LOCATOR = "//div[@class='RZYgph']//ancestor::div[@class='tuLXOo']" +
С комбобоксами то же самое. Думаю, что можно  из все свести к одному декоратору

2022-09-16 21:05 UTC, voropa commented on src/test/java/UI/Enums/Defects/Assignee.java
> +public enum Assignee implements BaseEnum {
Не думаю, что Assignee можно делат ьв виде emun - этовсе же динамические данные, которые могут поменяться/расшириться, а в enum оборачивают статические данные

2022-09-16 21:05 UTC, voropa commented on src/test/java/UI/Pages/DefectPages/DefectsPage.java
> +    @Override
Можно этот метод реализовать в base классе. Его реализаация же не меняется в классах-наследниках, он всегда возвращает driver.getCurrentUrl(), так какой смысл его оверрайдить везде

2022-09-16 21:05 UTC, voropa commented on src/test/java/UI/Pages/DefectPages/DefectsPage.java
> +    private final static By LAST_DEFECT_LOCATOR = By.xpath("(//a[@class='defect-title'])[1]");
Почему тут индексы в локаторах?

2022-09-16 21:05 UTC, voropa commented on src/test/java/UI/Pages/DefectPages/DefectsPage.java
> +    public void deleteDefects() {
Очень странная релизация метода. Думаю лучше будет сделать как то так:
List<WebElement> allDefects = driver.findElements(defectsLocator...)
int size = allDefects.size()
if( size > 1) {
for (int i = 1; i<= size; i++) {
deleteDefect(i);
}
}

2022-09-16 21:05 UTC, voropa commented on src/test/java/UI/Pages/ProjectPage.java
> +    public void invisibilityOfElementLocated() {
вероятно в названии этого метода должно быть слово wait

2022-09-16 21:05 UTC, voropa commented on src/test/java/UI/Pages/ProjectPage.java
> +        log.info("Deleting test cases if there are more than 3");
Почему тут захардкодано значение 3?

2022-09-16 21:05 UTC, voropa commented on src/test/java/UI/Pages/ProjectPage.java
> +        log.info("Selecting and transferring test cases to the created suite");
и тут тоже 3?

2022-09-16 21:05 UTC, voropa commented on src/test/java/UI/Pages/ProjectPage.java
> +        driver.findElement(By.xpath(String.format(CHOICE_OF_SUITE_DROPDOWN, "Smoke"))).click();
А тут название suite захардкодано

2022-09-16 21:05 UTC, voropa commented on src/test/java/UI/Pages/ProjectPage.java
> +        WebElement element = driver.findElement(By.xpath(String.format(DELETE_SUITE_BUTTON, "Smoke")));
И тут

2022-09-16 21:05 UTC, voropa commented on src/test/java/UI/Pages/TestRunsPages/CreateTestRunPage.java
> +        for (int i = 1; i < 4; i++) {
А тут 4 почему?

2022-09-17 07:58 UTC, PatternsG commented on src/test/java/UI/Pages/TestRunsPages/CreateTestRunPage.java
> +        for (int i = 1; i < 4; i++) {
Это для того, чтобы добавлялось 3 тест-кейска в ран. Но если их меньше - добавится то количество, что есть

2022-09-17 07:59 UTC, PatternsG commented on src/test/java/UI/Pages/ProjectPage.java
> +        log.info("Selecting and transferring test cases to the created suite");
Здесь тоже самое, что и с раном, добавляется 3 тест-кейска в сьют

2022-09-17 08:00 UTC, PatternsG commented on src/test/java/UI/Pages/ProjectPage.java
> +        log.info("Deleting test cases if there are more than 3");
Удаляются все тест-кейсы, оставляя только 3 последних

2022-09-17 08:01 UTC, PatternsG commented on src/test/java/UI/Elements/NewTestCasePage/Input.java
> +public class Input extends BaseElement {
У них локаторы разные, мне так удобнее было, я только из переименую по типу InputByTestCase/Suite и т.д.

2022-09-17 08:08 UTC, PatternsG commented on src/test/java/UI/Elements/NewTestCasePage/Input.java
> +public class Input extends BaseElement {
Сразу не обратил внимания, что там одинаковые локаторы

2022-09-18 13:11 UTC, PatternsG commented on src/test/java/UI/Pages/DefectPages/DefectsPage.java
> +    private final static By LAST_DEFECT_LOCATOR = By.xpath("(//a[@class='defect-title'])[1]");
Потому, что это локатор на последний созданный дефект

2022-09-18 14:20 UTC, closed without merging